export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'

export const GET_PAY_REQUEST = 'GET_PAY_REQUEST'
export const GET_PAY_SUCCESS = 'GET_PAY_SUCCESS'
export const GET_PAY_FAIL = 'GET_PAY_FAIL'
export const GET_PAY_RESET = 'GET_PAY_RESET'

export const GET_USER_ORDERS_REQUEST = 'GET_USER_ORDERS_REQUEST'
export const GET_USER_ORDERS_SUCCESS = 'GET_USER_ORDERS_SUCCESS'
export const GET_USER_ORDERS_FAIL = 'GET_USER_ORDERS_FAIL'
export const GET_USER_ORDERS_RESET = 'GET_USER_ORDERS_RESET'
